// End-to-end check with an isolated Chrome profile; no npm dependencies.
const {spawn}=require('node:child_process');
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),assert=require('node:assert/strict');
const debugPort=9400+Math.floor(Math.random()*1000);
const profile=fs.mkdtempSync(path.join(os.tmpdir(),'study-en-check-'));
const chrome=spawn(process.env.CHROME_PATH||'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',['--headless=new','--no-first-run','--no-proxy-server','--no-default-browser-check','--use-fake-ui-for-media-stream','--use-fake-device-for-media-stream',`--remote-debugging-port=${debugPort}`,`--user-data-dir=${profile}`,'about:blank'],{stdio:'ignore'});
const delay=ms=>new Promise(r=>setTimeout(r,ms));
(async()=>{
 let tabs;for(let i=0;i<60;i++){try{tabs=await(await fetch(`http://127.0.0.1:${debugPort}/json`)).json();break;}catch{await delay(200);}}if(!tabs)throw Error('Chrome did not start');
 const ws=new WebSocket(tabs.find(tab=>tab.type==='page').webSocketDebuggerUrl);await new Promise((r,j)=>{ws.onopen=r;ws.onerror=j;});
 let id=0;const pending=new Map(),errors=[];
 ws.onmessage=e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(m.error):p.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')errors.push(m.params.exceptionDetails);};
 const send=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}));});
 const evaluate=async expression=>{const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true,userGesture:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;};
 const wait=async expression=>{for(let i=0;i<100;i++){if(await evaluate(expression))return;await delay(100);}console.log("DIAGNOSTIC",await evaluate("({url:location.href,body:document.body?.innerText.slice(-2000)})"),errors);throw Error(`Timed out: ${expression}`);};
 const click=selector=>evaluate(`document.querySelector(${JSON.stringify(selector)}).click()`);
 const submitAnswer=async (value,review=true)=>{await evaluate(`(()=>{const fields=[...document.querySelectorAll('[data-blank]')];const parts=[...${JSON.stringify(value)}.replace(/[^a-z]/gi,'')];fields.forEach((field,i)=>{if(field.isConnected&&!field.readOnly){field.value=parts[i]||'';field.dispatchEvent(new Event('input',{bubbles:true}));}});})()`);if(review&&await evaluate("!!document.querySelector('#dictation-review-status')"))await click('#next-step');};
 const state=()=>evaluate("JSON.parse(localStorage.getItem('a-little-english-v2'))");
 const ready=()=>wait("document.querySelector('#library-summary')?.textContent.includes('770,611')");
 await send('Browser.grantPermissions',{origin:'http://127.0.0.1:5173',permissions:['audioCapture']});await send('Runtime.enable');await send('Page.enable');await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});
 await send('Page.navigate',{url:'http://127.0.0.1:5173'});await ready();
 await evaluate("localStorage.removeItem('a-little-english-v2');localStorage.setItem('a-little-english-v1',JSON.stringify({completed:true,dates:['2026-09-20'],lastPractice:'2026-09-20',reviews:1}));location.reload()");await delay(300);await ready();
 assert.equal(Object.keys((await state()).cards).length,3);
 await evaluate("localStorage.removeItem('a-little-english-v1');localStorage.removeItem('a-little-english-v2');location.reload()");await delay(300);await ready();
 fs.writeFileSync(path.join(os.tmpdir(),'study-en-v2-desktop.png'),Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
 await click('#start-lesson');await click('#next-step');await click('#close-lesson');await evaluate('location.reload()');await delay(300);await ready();await click('#start-lesson');assert.equal((await state()).session.index,1);
 let madeMistake=false;
 async function finishExercises(injectMistake=false){
  for(let i=0;i<120;i++){
   if(await evaluate("!!document.querySelector('#finish-lesson')"))return;
   const saved=await state(),step=saved.session.steps[saved.session.index];
   if(step.type==='choice'){
    if(injectMistake&&!madeMistake){await click(`[data-option="${step.options.findIndex(o=>o!==step.answer)}"]`);assert.equal(await evaluate("document.querySelector('#next-step').hidden"),true);madeMistake=true;}
    await click(`[data-option="${step.options.indexOf(step.answer)}"]`);
   }else if(['gap','sentence-gap','spell','listen'].includes(step.type))await submitAnswer(step.answer);
   else await click('#next-step');
  }console.log('LESSON DIAGNOSTIC',await state(),errors);throw Error('Lesson never finished');
 }
 await finishExercises(true);assert.equal(Object.keys((await state()).cards).length,5);assert.equal((await state()).cards.i.mistakes,1);await click('#finish-lesson');
 await click('[data-view="home"]');assert((await evaluate("document.querySelector('#start-lesson').textContent")).includes('今日目标完成'));
 await click('[data-view="path"]');assert.equal(await evaluate("document.querySelectorAll('#course-grid .course-card').length"),12);
 await evaluate("document.querySelector('#course-filter').value='core';document.querySelector('#course-filter').dispatchEvent(new Event('change'))");assert((await evaluate("document.querySelector('#course-pagination').textContent")).includes('586'));
 await click('[data-course="core-0"]');assert((await state()).session.wordKeys.length>0);await click('#close-lesson');
 await click('[data-view="grammar"]');await click('[data-course="grammar-1"]');await click('#replace-session');await finishExercises();await click('#finish-lesson');assert((await state()).grammar.includes('grammar-1'));
 await click('[data-view="speaking"]');await click('[data-course="scene-1"]');await click('#record-button');await wait("document.querySelector('#record-status').textContent.includes('正在录音')");await delay(300);await click('#record-button');await wait("!document.querySelector('#record-playback').hidden");await finishExercises();await click('#finish-lesson');assert((await state()).scenes.includes('scene-1'));
 await click('[data-view="dictionary"]');await evaluate("document.querySelector('#dictionary-query').value='apple';document.querySelector('#dictionary-form').requestSubmit()");await wait("document.querySelector('#dictionary-results')?.textContent.includes('苹果')");assert((await evaluate("document.querySelector('#dictionary-status').textContent")).includes('找到'));
 await click('[data-add-word="0"]');await finishExercises();await click('#finish-lesson');assert(Object.keys((await state()).cards).length>=6);
 await click('[data-view="settings"]');await evaluate("document.querySelector('#daily-target').value='10';document.querySelector('#daily-target').dispatchEvent(new Event('change'))");assert.equal((await state()).settings.daily,10);
 const audioResponse=await fetch('http://127.0.0.1:5173/api/audio?text=I&voice=jenny&speed=normal');assert.equal(audioResponse.status,200);assert.equal(audioResponse.headers.get('content-type'),'audio/mpeg');assert((await audioResponse.arrayBuffer()).byteLength>1000);
 for(const width of [390,320]){await send('Emulation.setDeviceMetricsOverride',{width,height:844,deviceScaleFactor:1,mobile:true});for(const view of ['home','words','library','path','grammar','speaking','reading','listening','dictionary','settings']){await click(`[data-view="${view}"]`);assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true,`Overflow: ${view} ${width}`);}}
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await click('[data-view="home"]');fs.writeFileSync(path.join(os.tmpdir(),'study-en-v2-mobile.png'),Buffer.from((await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true})).data,'base64'));
 // An old saved lesson must gain phonetics and the new gap step without losing its place.
 await evaluate("const s=JSON.parse(localStorage.getItem('a-little-english-v2'));s.session={kind:'words',title:'补字母验证',wordKeys:['please'],wrong:[],firstTry:0,index:0,steps:[{type:'learn',word:'please',key:'please',meaning:'请',phonetic:''},{type:'spell',key:'please',title:'请',answer:'please'},{type:'spell',title:'我想要水。',answer:'I want water.'}]};localStorage.setItem('a-little-english-v2',JSON.stringify(s));location.reload()");await delay(300);await ready();await click('#start-lesson');
 assert.equal(await evaluate("document.querySelector('.word-phonetic').textContent"),'/pliːz/');assert.equal(await evaluate("getComputedStyle(document.querySelector('.word-meaning')).textAlign"),'center');
 fs.writeFileSync(path.join(os.tmpdir(),'study-en-word-card.png'),Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
 await click('#next-step');let gap=(await state()).session.steps[(await state()).session.index];assert.equal(gap.type,'gap');
 await submitAnswer('z');assert.equal(await evaluate("document.querySelector('#next-step').hidden"),true);
 fs.writeFileSync(path.join(os.tmpdir(),'study-en-letter-gap.png'),Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
 await submitAnswer(gap.answer);assert.equal(await evaluate("document.querySelector('#feedback').hidden"),true);
 gap=(await state()).session.steps[(await state()).session.index];assert.equal(gap.type,'gap');assert.equal(gap.answer.length,2);
 assert.equal(await evaluate("!!document.querySelector('#answer-input')||!!document.querySelector('#check-answer')"),false);
 await evaluate(`const field=document.querySelector('[data-blank="0"]');field.focus();field.value=${JSON.stringify(gap.answer[0])};field.dispatchEvent(new InputEvent('input',{bubbles:true,isComposing:true}));`);
 assert.equal(await evaluate("document.querySelectorAll('[data-blank][readonly]').length"),0);
 await evaluate("document.querySelector('[data-blank=\"0\"]').dispatchEvent(new CompositionEvent('compositionend',{bubbles:true}))");
 assert.equal(await evaluate("document.activeElement.dataset.blank"),'1');assert.equal(await evaluate("document.querySelectorAll('.blank-error').length"),0);
 await send('Input.insertText',{text:'z'});
 assert.equal(await evaluate("document.activeElement.getAttribute('aria-invalid')"),'true');assert.equal(await evaluate("document.activeElement.selectionEnd-document.activeElement.selectionStart"),1);
assert.equal(await evaluate("document.querySelectorAll('[data-blank][readonly]').length"),1);assert.equal(await evaluate("document.querySelector('[data-blank=\"0\"]').value"),gap.answer[0]);
 const partialScore=(await state()).session.firstTry;
 fs.writeFileSync(path.join(os.tmpdir(),'study-en-inline-letters.png'),Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
 const beforeReload=await state();await click('#close-lesson');await evaluate('location.reload()');await delay(300);await ready();await click('#start-lesson');assert.equal((await state()).session.index,beforeReload.session.index);assert.equal((await state()).session.steps.length,beforeReload.session.steps.length);assert.equal(await evaluate("document.querySelectorAll('[data-blank][readonly]').length"),1);assert.equal((await state()).session.firstTry,partialScore);assert.deepEqual((await state()).session.steps.map(s=>s.masked),beforeReload.session.steps.map(s=>s.masked));
 for(const round of [0,1]){const saved=await state(),current=saved.session.steps[saved.session.index];assert.equal(current.type,'gap');assert(current.answer.length>=(round===0?2:3));if(round===1){await evaluate(`const clipboardData=new DataTransfer();clipboardData.setData('text',${JSON.stringify(current.answer)});document.querySelector('[data-blank]').dispatchEvent(new ClipboardEvent('paste',{bubbles:true,cancelable:true,clipboardData}));`);}else await submitAnswer(current.answer);assert.equal((await state()).session.index,saved.session.index+1);}
 assert.equal((await state()).session.steps[(await state()).session.index].type,'spell');await submitAnswer('please');
 for(const count of [1,2]){
  const saved=await state(),current=saved.session.steps[saved.session.index],letters=current.answer.replace(/[^a-z]/gi,'').length;
  assert.equal(current.type,'sentence-gap');assert.equal(current.missing.length,count);assert.equal(await evaluate("document.querySelectorAll('[data-blank]').length"),letters);assert.equal(await evaluate("[...document.querySelectorAll('[data-blank]')].every(x=>x.maxLength===1)"),true);
  assert.equal(await evaluate("document.querySelector('.letter-sentence').getBoundingClientRect().bottom < document.querySelector('.gap-card .word-meaning').getBoundingClientRect().top"),true);
  assert.equal(await evaluate("getComputedStyle(document.querySelector('[data-blank]')).backgroundColor"),'rgba(0, 0, 0, 0)');
  if(count===2){await submitAnswer(current.missing[0]+' zzzzz');assert.equal(await evaluate("document.querySelectorAll('[data-blank][readonly]').length"),current.missing[0].length);await click('#close-lesson');await evaluate('location.reload()');await delay(300);await ready();await click('#start-lesson');assert.equal(await evaluate("document.querySelectorAll('[data-blank][readonly]').length"),current.missing[0].length);fs.writeFileSync(path.join(os.tmpdir(),'study-en-letter-sentence.png'),Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));}
  await submitAnswer('wrong');assert.equal(await evaluate("document.querySelector('#next-step').hidden"),true);await submitAnswer(current.answer);assert.equal((await state()).session.index,saved.session.index+1);
 }
 assert.equal((await state()).session.steps[(await state()).session.index].type,'spell');await finishExercises();await click('#finish-lesson');
 await click('[data-view="library"]');assert.equal(await evaluate("document.querySelector('.stat-0 strong').textContent"),'6,005');
 await evaluate("document.querySelector('#collection-select').value='cet4';document.querySelector('#collection-select').dispatchEvent(new Event('change'))");assert.equal(await evaluate("document.querySelector('.stat-0 strong').textContent"),'3,849');assert.equal(await evaluate("document.querySelectorAll('#library-grid .library-word').length"),24);
 await click('#library-pagination [data-page="2"]');assert((await evaluate("document.querySelector('#library-pagination').textContent")).includes('第 2'));
 const target=await evaluate("(async()=>{const e=await(await fetch('data/exams.json')).json();const s=JSON.parse(localStorage.getItem('a-little-english-v2'));return e.find(w=>w.tags.split(' ').includes('cet4')&&w.tags.split(' ').includes('cet6')&&!s.cards[w.word.toLowerCase()]&&/^[a-z]{4,}$/.test(w.word)).word})()");
 await evaluate(`document.querySelector('#library-search').value=${JSON.stringify(target)};document.querySelector('#library-search').dispatchEvent(new Event('input'))`);assert((await evaluate("document.querySelector('#library-pagination').textContent")).includes('第 1'));
 await click(`[data-study-word="${target}"]`);await finishExercises();await click('#finish-lesson');await click('[data-view="library"]');assert.equal(await evaluate(`document.querySelector('[data-study-word="${target}"]').closest('article').classList.contains('is-learned')`),true);
 await evaluate("document.querySelector('#collection-select').value='cet6';document.querySelector('#collection-select').dispatchEvent(new Event('change'))");assert.equal(await evaluate("document.querySelector('.stat-0 strong').textContent"),'5,407');assert.equal(await evaluate(`document.querySelector('[data-study-word="${target}"]').closest('article').classList.contains('is-learned')`),true);
 await click('#set-collection');assert.equal((await state()).settings.collection,'cet6');await evaluate('location.reload()');await delay(300);await ready();await click('[data-view="library"]');assert.equal(await evaluate("document.querySelector('#collection-select').value"),'cet6');
 await evaluate("document.querySelector('#library-filter').value='new';document.querySelector('#library-filter').dispatchEvent(new Event('change'))");assert.equal(await evaluate("document.querySelectorAll('#library-grid .is-learned').length"),0);
 await evaluate("document.querySelector('#library-filter').value='learned';document.querySelector('#library-filter').dispatchEvent(new Event('change'))");assert.equal(await evaluate("document.querySelectorAll('#library-grid .status-new').length"),0);
 await send('Emulation.setDeviceMetricsOverride',{width:1440,height:1100,deviceScaleFactor:1,mobile:false});fs.writeFileSync(path.join(os.tmpdir(),'study-en-collections-desktop.png'),Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);fs.writeFileSync(path.join(os.tmpdir(),'study-en-collections-mobile.png'),Buffer.from((await send('Page.captureScreenshot',{format:'png',captureBeyondViewport:true})).data,'base64'));
 await click('[data-view="home"]');await click('#start-lesson');const assigned=(await state()).session;assert(assigned.wordKeys.length>0);assert.equal(await evaluate(`(async()=>{const e=await(await fetch('data/exams.json')).json();return ${JSON.stringify(assigned.wordKeys)}.every(k=>e.some(w=>w.word.toLowerCase()===k&&w.tags.split(' ').includes('cet6')))})()`),true);await click('#close-lesson');
 // Migrate a previously correct whole-word blank to individual letters without losing credit.
 await evaluate(`const s=JSON.parse(localStorage.getItem('a-little-english-v2'));s.session={kind:'grammar',id:'grammar-5',title:'逐字母句子验证',progressionVersion:2,index:0,firstTry:1,wrong:[],wordKeys:[],steps:[{type:'sentence-gap',title:'补一个单词',sentence:"I don't want water!",translation:'我不想要水！',parts:[{text:'I ',blank:false},{text:"don't",blank:true},{text:' want water!',blank:false}],missing:["don't"],answer:"don't",blankState:{values:["don't"],locked:[true],counted:true,submitted:true}},{type:'spell',title:'我不想要水！',answer:"I don't want water!"}]};localStorage.setItem('a-little-english-v2',JSON.stringify(s));location.reload()`);await delay(300);await ready();await click('#start-lesson');assert.equal((await state()).session.index,1);assert.equal((await state()).session.firstTry,1);assert.equal((await state()).session.steps[0].blankState.locked.filter(Boolean).length,4);
 assert.equal(await evaluate("document.querySelector('#lesson-title').textContent"),'写出完整句子');assert.equal(await evaluate("[...document.querySelectorAll('.fixed-punctuation')].map(x=>x.textContent).join('')"),"'!");assert.equal(await evaluate("document.querySelector('#answer-input')===null"),true);
 assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);fs.writeFileSync(path.join(os.tmpdir(),'study-en-full-sentence-lines.png'),Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));await finishExercises();assert.equal((await state()).session,null);
 // Adaptive widths, readable letter slots, and live resizing without losing answers.
 await click('#finish-lesson');
 await send('Emulation.setDeviceMetricsOverride',{width:1200,height:1050,deviceScaleFactor:1,mobile:false});
 const adaptiveSteps=[{type:'spell',title:'我想要水，谢谢。',answer:'I want water, please.'},{type:'spell',title:'每天我都喜欢和朋友一起学习英语。',answer:'I enjoy learning English with my friends every day.'},{type:'spell',key:'water',title:'水',answer:'water'}];
 await evaluate(`const s=JSON.parse(localStorage.getItem('a-little-english-v2'));s.session={kind:'grammar',id:'grammar-5',title:'自适应句子验证',progressionVersion:2,index:0,firstTry:0,wrong:[],wordKeys:[],steps:${JSON.stringify(adaptiveSteps)}};localStorage.setItem('a-little-english-v2',JSON.stringify(s));location.reload()`);await delay(300);await ready();await click('#start-lesson');await delay(100);
 const geometry=()=>evaluate(`(()=>{const d=document.querySelector('#lesson-dialog'),l=document.querySelector('.letter-sentence');return {width:d.getBoundingClientRect().width,font:parseFloat(getComputedStyle(l).fontSize),rows:new Set([...l.children].map(x=>Math.round(x.getBoundingClientRect().top))).size,overflow:d.scrollWidth>d.clientWidth,wordSplit:[...l.children].some(w=>Math.max(...[...w.children].map(c=>c.getBoundingClientRect().top))-Math.min(...[...w.children].map(c=>c.getBoundingClientRect().top))>parseFloat(getComputedStyle(l).fontSize))}})()`);
 let g=await geometry();assert(g.width>600);assert.equal(g.rows,1);assert.equal(g.overflow,false);
 fs.writeFileSync(path.join(os.tmpdir(),'study-en-adaptive-desktop.png'),Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
 await submitAnswer('Izzzzzzzzzzzzzzzz');assert.equal(await evaluate("document.querySelectorAll('[readonly][data-blank]').length"),1);
 for(const width of [390,320,768,1200]){await send('Emulation.setDeviceMetricsOverride',{width,height:1050,deviceScaleFactor:1,mobile:width<640});await delay(100);g=await geometry();assert(g.width<=width-28);assert(g.font>=22);assert.equal(g.overflow,false);assert.equal(g.wordSplit,false);assert.equal(await evaluate("document.querySelectorAll('[readonly][data-blank]').length"),1);}
 await submitAnswer(adaptiveSteps[0].answer);await delay(100);g=await geometry();assert(g.width>800&&g.width<=960);assert.equal(g.overflow,false);
 for(const width of [320,390,768,1200]){await send('Emulation.setDeviceMetricsOverride',{width,height:1050,deviceScaleFactor:1,mobile:width<640});await delay(100);g=await geometry();assert.equal(g.overflow,false);assert.equal(g.wordSplit,false);assert(g.font>=22);}
 await submitAnswer(adaptiveSteps[1].answer);await delay(100);assert.equal((await geometry()).width,600);await submitAnswer('water');assert.equal(await evaluate("document.querySelector('#lesson-dialog').style.width"),'');
 // Delayed audio preparation is shared with clicks, and abandoned playback stays silent.
 await click('#finish-lesson');
 await evaluate(`const s=JSON.parse(localStorage.getItem('a-little-english-v2'));s.settings.voice='jenny';s.session={kind:'alphabet',id:'alphabet',title:'语音预加载验证',progressionVersion:2,index:0,firstTry:0,wrong:[],wordKeys:[],steps:[{type:'letter',word:'Q',title:'Q'},{type:'letter',word:'Z',title:'Z'}]};localStorage.setItem('a-little-english-v2',JSON.stringify(s));location.reload()`);await delay(300);await ready();
 await evaluate(`(async()=>{window.audioFixture=await(await fetch('/api/audio?text=I&voice=jenny&speed=normal')).blob();window.audioRequests=[];window.audioReleases=[];window.playCalls=0;window.originalFetch=window.fetch;window.originalPlay=Audio.prototype.play;window.fetch=(url,options)=>String(url).startsWith('/api/audio?')?new Promise(resolve=>{audioRequests.push(String(url));audioReleases.push(()=>resolve(new Response(audioFixture)));}):originalFetch(url,options);Audio.prototype.play=function(){playCalls++;this.onplaying?.();return Promise.resolve();};})()`);
 await click('#start-lesson');await wait('audioRequests.length===2');assert.equal(await evaluate('playCalls'),0);
 await click('[data-speed="normal"]');assert.equal(await evaluate("document.querySelector('[data-speed=normal]').classList.contains('audio-loading')"),true);assert.equal(await evaluate("document.querySelector('[data-speed=normal]').classList.contains('playing')"),false);assert.equal(await evaluate('audioRequests.length'),2);
 await evaluate('audioReleases[0]()');await wait('playCalls===1');assert.equal(await evaluate("document.querySelector('[data-speed=normal]').classList.contains('playing')"),true);
 await click('[data-speed="normal"]');await wait('playCalls===2');assert.equal(await evaluate('audioRequests.length'),2);
 await click('[data-speed="slow"]');await click('#next-step');await evaluate('audioReleases[1]()');await delay(50);assert.equal(await evaluate('playCalls'),2);
 await click('#close-lesson');await evaluate('window.fetch=originalFetch;Audio.prototype.play=originalPlay');
 // Dictation hides the translation until a mistake, including across saved sessions.
 await evaluate(`const s=JSON.parse(localStorage.getItem('a-little-english-v2'));s.session={kind:'words',title:'听写提示验证',progressionVersion:2,index:0,firstTry:0,wrong:[],wordKeys:['water','please'],steps:[{type:'listen',title:'听声音，写出这个词。',answer:'water',key:'water'},{type:'listen',title:'听声音，写出这个词。',answer:'please',key:'please'},{type:'spell',title:'写出英语：水',answer:'water',key:'water'}]};localStorage.setItem('a-little-english-v2',JSON.stringify(s));location.reload()`);await delay(300);await ready();await click('#start-lesson');
 const hintVisible=()=>evaluate("getComputedStyle(document.querySelector('.gap-card .word-meaning')).display!=='none'");
 assert.equal(await hintVisible(),false);await submitAnswer('w');assert.equal(await hintVisible(),false);
 await click('#close-lesson');await evaluate('location.reload()');await delay(300);await ready();await click('#start-lesson');assert.equal(await hintVisible(),false);
 await submitAnswer('wz');assert.equal(await hintVisible(),true);assert.equal(await evaluate("document.querySelector('.gap-card .word-meaning').textContent"),'水');
 await click('#close-lesson');await evaluate('location.reload()');await delay(300);await ready();await click('#start-lesson');assert.equal(await hintVisible(),true);
 await submitAnswer('wa');assert.equal(await hintVisible(),true);await submitAnswer('water');assert.equal((await state()).session.index,1);assert.equal(await hintVisible(),false);
 await submitAnswer('please');assert.equal((await state()).session.index,2);assert.equal(await hintVisible(),true);await submitAnswer('water');assert.equal((await state()).session,null);
 // Independent reviews withhold letter feedback until the whole word is filled.
 await click('#finish-lesson');
 await evaluate(`const s=JSON.parse(localStorage.getItem('a-little-english-v2'));const d=new Date();d.setDate(d.getDate()-1);const yesterday=[d.getFullYear(),String(d.getMonth()+1).padStart(2,'0'),String(d.getDate()).padStart(2,'0')].join('-');for(const key of ['water','tea'])s.cards[key]={stage:0,added:yesterday,last:yesterday,due:yesterday,mistakes:0,lapses:0};s.session={kind:'words',memoryVersion:1,title:'独立复习验证',progressionVersion:2,index:0,firstTry:0,wrong:[],wordKeys:['water','tea'],steps:['water','tea'].map(key=>({type:'listen',title:'听声音，独立写出这个词。',answer:key,key,wholeAnswer:true,assessment:'review'}))};localStorage.setItem('a-little-english-v2',JSON.stringify(s));location.reload()`);await delay(300);await ready();await click('#start-lesson');
 await submitAnswer('z');assert.equal(await hintVisible(),false);assert.equal(await evaluate("document.querySelectorAll('.filled,.blank-error').length"),0);assert.equal((await state()).session.wrong.length,0);
 await click('#close-lesson');await evaluate('location.reload()');await delay(300);await ready();await click('#start-lesson');assert.equal(await hintVisible(),false);assert.equal(await evaluate("document.querySelector('[data-blank]').value"),'z');
 await submitAnswer('zater');assert.equal(await hintVisible(),true);assert.equal(await evaluate("document.querySelectorAll('[data-blank][readonly]').length"),4);assert.equal((await state()).session.steps[0].blankState.hintUsed,true);
 await submitAnswer('water');assert.equal((await state()).session.index,1);assert.equal(await hintVisible(),false);await submitAnswer('t');assert.equal(await evaluate("document.querySelectorAll('[data-blank][readonly]').length"),0);await submitAnswer('tea');assert.equal((await state()).session,null);
 let memory=(await state()).cards;assert.equal(memory.water.independentDays,0);assert.equal(memory.water.hintUses,1);assert.equal(memory.tea.independentDays,1);assert.equal(memory.tea.hintUses,0);
 await click('#finish-lesson');await click('[data-practice-word="tea"]');assert.equal((await state()).session.steps[0].wholeAnswer,true);await finishExercises();memory=(await state()).cards;assert.equal(memory.tea.independentDays,1);await click('#finish-lesson');
 // Graduated help, answer visibility, retry scheduling and assistance survive reload.
 await evaluate(`const s=JSON.parse(localStorage.getItem('a-little-english-v2'));s.session={kind:'words',title:'分层提示验证',progressionVersion:2,index:0,firstTry:0,wrong:[],wordKeys:['water'],steps:[{type:'listen',title:'听声音写单词',key:'water',answer:'water',wholeAnswer:true},{type:'letter',word:'A'},{type:'letter',word:'B'}]};localStorage.setItem('a-little-english-v2',JSON.stringify(s));location.reload()`);await delay(300);await ready();await click('#start-lesson');
 await submitAnswer('woter');assert.equal(await evaluate("document.querySelector('#feedback').textContent.includes('第 2 个')"),true);assert.equal(await evaluate("!!document.querySelector('#letter-hint')"),false);assert.equal(await evaluate("!!document.querySelector('#answer-help [data-speak]')"),true);
 await submitAnswer('woter');assert.equal(await evaluate("!!document.querySelector('#letter-hint')"),true);await click('#letter-hint');assert.equal(await evaluate("document.querySelector('.letter-hint').textContent.includes('a')"),true);assert.equal((await state()).session.steps[0].blankState.hintUsed,true);
 await click('#reveal-answer');assert.equal(await evaluate("document.querySelector('.answer-reveal strong').textContent"),'water');assert.equal((await state()).session.steps.length,4);assert.equal((await state()).session.steps[3].retry,true);
 await click('#close-lesson');await evaluate('location.reload()');await delay(300);await ready();await click('#start-lesson');assert.equal(await evaluate("!!document.querySelector('#hide-answer')"),true);assert.equal((await state()).session.steps.length,4);
 await click('#hide-answer');assert.equal(await evaluate("document.querySelectorAll('[data-blank][readonly]').length"),0);assert.equal(await evaluate("[...document.querySelectorAll('[data-blank]')].every(x=>x.value==='')"),true);
 await click('#reveal-answer');assert.equal((await state()).session.steps.length,4);await click('#hide-answer');await submitAnswer('water');assert.equal((await state()).session.index,1);await click('#next-step');await click('#next-step');assert.equal((await state()).session.steps[(await state()).session.index].retry,true);
 await click('#reveal-answer');assert.equal((await state()).session.steps.length,4);await click('#hide-answer');await submitAnswer('water');assert.equal((await state()).session,null);assert((await state()).cards.water.answerUses>=1);assert.equal((await state()).cards.water.independentDays,0);
 // Reading lookup, notebook persistence, comprehension, daily priority and role-play.
 await click('#finish-lesson');await click('[data-view="reading"]');assert.equal(await evaluate("document.querySelectorAll('[data-reading-open]').length"),32);await click('[data-reading-open="read-1"]');
 assert.equal(await evaluate("document.querySelectorAll('.reading-token').length"),26);
 await click('[data-reading-word="cup"]');await wait("!document.querySelector('#save-reading-word').disabled");assert.equal(await evaluate("document.querySelector('#reading-word-dialog').open"),true);assert.equal(await evaluate("document.querySelectorAll('#reading-word-content [data-speak]').length"),2);
 await click('#save-reading-word');await click('#save-reading-word');assert.equal((await state()).readingWords.filter(w=>w.word==='cup').length,1);assert.equal((await state()).cards.cup,undefined);await click('#close-reading-word');
 await click('[data-reading-question="0"][data-reading-option="1"]');assert.equal((await state()).readingProgress['read-1'].completed,null);await click('[data-reading-question="0"][data-reading-option="0"]');await click('[data-reading-question="1"][data-reading-option="1"]');assert((await state()).readingProgress['read-1'].completed);
 await evaluate('location.reload()');await delay(300);await ready();await click('[data-view="reading"]');assert.equal((await state()).readingWords.length,1);await click('[data-reading-open="read-1"]');assert.equal(await evaluate("document.querySelector('[data-reading-word=cup]').classList.contains('is-saved')"),true);
 for(const width of [320,390,1440]){await send('Emulation.setDeviceMetricsOverride',{width,height:1050,deviceScaleFactor:1,mobile:width<640});assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);}
 await evaluate("document.querySelector('#reading-article').scrollIntoView()");await delay(150);fs.writeFileSync(path.join(os.tmpdir(),'study-en-reading-desktop.png'),Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));
 await send('Emulation.setDeviceMetricsOverride',{width:390,height:844,deviceScaleFactor:1,mobile:true});await click('[data-reading-word=water]');await wait("!document.querySelector('#save-reading-word').disabled");assert.equal(await evaluate("document.querySelector('#reading-word-dialog').scrollWidth<=document.querySelector('#reading-word-dialog').clientWidth"),true);fs.writeFileSync(path.join(os.tmpdir(),'study-en-reading-word-mobile.png'),Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));await click('#close-reading-word');
 await click('#study-reading-words');assert((await state()).session.wordKeys.includes('cup'));await finishExercises();await click('#finish-lesson');assert((await state()).cards.cup);
 await evaluate("{const s=JSON.parse(localStorage.getItem('a-little-english-v2'));s.scenes=Array.from({length:8},(_,i)=>'scene-'+(i+1));localStorage.setItem('a-little-english-v2',JSON.stringify(s));location.reload();}");await delay(300);await ready();
 await click('[data-view="speaking"]');assert.equal(await evaluate("document.querySelectorAll('#speaking-grid article').length"),24);await click('[data-role-scene="scene-9"]');assert.equal(await evaluate("document.querySelector('.role-reference').open"),false);assert.equal((await state()).session.steps[0].partner,'When can we meet?');await click('.role-reference summary');assert.equal(await evaluate("document.querySelector('.role-reference').open"),true);await finishExercises();await click('#finish-lesson');assert((await state()).scenes.includes('scene-9'));
 // Every stage is directly selectable; complete advanced grammar and listening.
 for(const view of ['grammar','speaking','reading','listening']){await click(`[data-view="${view}"]`);for(const level of ['入门','基础','中级','高级']){await evaluate(`{const select=document.querySelector('#${view}-level');select.value=${JSON.stringify(level)};select.dispatchEvent(new Event('change'));}`);const selector=view==='reading'?'#reading-list':`#${view}-grid`;assert((await evaluate(`document.querySelectorAll('${selector} article').length`))>=4);assert.equal(await evaluate('document.documentElement.scrollWidth<=innerWidth'),true);}}
 await evaluate("{const s=JSON.parse(localStorage.getItem('a-little-english-v2'));s.grammar=Array.from({length:18},(_,i)=>'grammar-'+(i+1));s.listenings=Array.from({length:12},(_,i)=>'listen-'+(i+1));localStorage.setItem('a-little-english-v2',JSON.stringify(s));location.reload();}");await delay(300);await ready();
 await click('[data-view="grammar"]');await click('[data-course="grammar-19"]');await finishExercises();await click('#finish-lesson');assert((await state()).grammar.includes('grammar-19'));
 await click('[data-view="listening"]');await click('[data-listening-course="listen-13"]');assert.equal((await state()).session.kind,'listening');assert.equal(await evaluate("document.querySelector('.audio-passage details').open"),false);assert((await evaluate("document.querySelectorAll('.audio-passage [data-speak]').length"))>2);await finishExercises();await click('#finish-lesson');assert((await state()).listenings.includes('listen-13'));
 await evaluate('location.reload()');await delay(300);await ready();assert((await state()).listenings.includes('listen-13'));
 // Unlocks are per module; entry guards still apply when disabled buttons are manipulated.
 await evaluate("{const s=JSON.parse(localStorage.getItem('a-little-english-v2'));s.session=null;s.grammar=[];s.scenes=[];s.listenings=[];s.readingProgress={};localStorage.setItem('a-little-english-v2',JSON.stringify(s));location.reload();}");await delay(300);await ready();
 for(const [view,selector] of [['grammar','data-course'],['speaking','data-course'],['reading','data-reading-open'],['listening','data-listening-course']]){await click(`[data-view="${view}"]`);const root=view==='reading'?'reading-list':view+'-grid';assert.equal(await evaluate(`document.querySelectorAll('#${root} [${selector}]:not([disabled])').length`),1);assert.equal(await evaluate(`document.querySelector('#${view}-level option[value="高级"]').disabled`),true);}
 await click('[data-view="grammar"]');await evaluate("document.querySelector('[data-course=grammar-19]').disabled=false");await click('[data-course="grammar-19"]');assert.equal((await state()).session,null);
 await click('[data-course="grammar-1"]');await finishExercises();await click('#finish-lesson');assert.equal(await evaluate("document.querySelector('[data-course=grammar-2]').disabled"),false);assert.equal(await evaluate("document.querySelector('[data-course=grammar-3]').disabled"),true);
 await evaluate("{const s=JSON.parse(localStorage.getItem('a-little-english-v2'));s.grammar=['grammar-1','grammar-2','grammar-3'];localStorage.setItem('a-little-english-v2',JSON.stringify(s));location.reload();}");await delay(300);await ready();await click('[data-view="grammar"]');await click('[data-course="grammar-4"]');await finishExercises();await click('#finish-lesson');assert.equal(await evaluate("document.querySelector('#grammar-level option[value=基础]').disabled"),false);assert.equal(await evaluate("document.querySelector('[data-course=grammar-5]').disabled"),false);assert.equal(await evaluate("document.querySelector('[data-course=grammar-6]').disabled"),true);
 await evaluate('location.reload()');await delay(300);await ready();await click('[data-view="grammar"]');assert.equal(await evaluate("document.querySelector('[data-course=grammar-5]').disabled"),false);await click('[data-view="reading"]');assert.equal(await evaluate("document.querySelector('[data-reading-open=read-2]').disabled"),true);
 // Expanded reading keeps sequential access and shows skill-specific explanations.
 await evaluate("{const s=JSON.parse(localStorage.getItem('a-little-english-v2'));s.readingProgress={};for(const id of ['read-1','read-2','read-7','read-8'])s.readingProgress[id]={answers:[0,0],completed:'2026-09-23'};localStorage.setItem('a-little-english-v2',JSON.stringify(s));location.reload();}");await delay(300);await ready();await click('[data-view="reading"]');assert.equal(await evaluate("document.querySelector('#reading-summary').textContent.includes('86')"),true);assert.equal(await evaluate("document.querySelector('[data-reading-open=read-17]').disabled"),false);assert.equal(await evaluate("document.querySelector('[data-reading-open=read-3]').disabled"),true);
 await click('[data-reading-open="read-17"]');assert.equal(await evaluate("document.querySelectorAll('.reading-skill').length"),3);await click('[data-reading-question="0"][data-reading-option="1"]');assert.equal(await evaluate("document.querySelectorAll('.reading-explanation').length"),0);await click('[data-reading-question="0"][data-reading-option="0"]');assert.equal(await evaluate("document.querySelector('.reading-explanation').textContent.includes('开门时间')"),true);await click('[data-reading-question="1"][data-reading-option="1"]');await click('[data-reading-question="2"][data-reading-option="2"]');assert.equal(await evaluate("document.querySelector('[data-reading-open=read-18]').disabled"),false);
 // Continuous word colouring, saved display mode, structured exercises and plain recall.
 await evaluate("{const s=JSON.parse(localStorage.getItem('a-little-english-v2'));s.session=null;delete s.cards.government;delete s.cards.teacher;localStorage.setItem('a-little-english-v2',JSON.stringify(s));location.reload();}");await delay(300);await ready();
 async function openStructuredWord(word){await click('[data-view="library"]');await evaluate(`document.querySelector('#collection-select').value='all';document.querySelector('#collection-select').dispatchEvent(new Event('change'));document.querySelector('#library-filter').value='all';document.querySelector('#library-filter').dispatchEvent(new Event('change'));document.querySelector('#library-search').value=${JSON.stringify(word)};document.querySelector('#library-search').dispatchEvent(new Event('input'));`);await click(`[data-study-word="${word}"]`);}
 await openStructuredWord('government');assert.equal(await evaluate("document.querySelector('#structured-word').textContent"),'government');assert.equal(await evaluate("document.querySelectorAll('.word-chunk').length"),2);assert.equal(await evaluate("!!document.querySelector('[data-structure-mode=syllables]')"),false);
 await click('[data-structure-mode="plain"]');assert.equal(await evaluate("document.querySelectorAll('.word-chunk').length"),0);await click('#close-lesson');await evaluate('location.reload()');await delay(300);await ready();await click('#start-lesson');assert.equal(await evaluate("document.querySelectorAll('.word-chunk').length"),0);await click('[data-structure-mode="morphemes"]');
 for(const width of [320,390,1200]){await send('Emulation.setDeviceMetricsOverride',{width,height:900,deviceScaleFactor:1,mobile:width<640});assert.equal(await evaluate("document.querySelector('#lesson-dialog').scrollWidth<=document.querySelector('#lesson-dialog').clientWidth"),true);}
 fs.writeFileSync(path.join(os.tmpdir(),'study-en-word-structure.png'),Buffer.from((await send('Page.captureScreenshot',{format:'png'})).data,'base64'));await finishExercises();await click('#finish-lesson');
 await openStructuredWord('teacher');await click('[data-structure-mode="syllables"]');assert.equal(await evaluate("document.querySelector('.stressed-chunk').textContent"),'teach');await click('#next-step');let structureSession=(await state()).session;await click(`[data-option="${structureSession.steps[structureSession.index].options.indexOf(structureSession.steps[structureSession.index].answer)}"]`);
 assert.equal((await state()).session.steps[(await state()).session.index].title,'听完整单词，有几个音节？');await click('[data-option="0"]');assert.equal(await evaluate("document.querySelector('#next-step').hidden"),true);await click('[data-option="1"]');await click('[data-option="0"]');assert.equal((await state()).session.steps[(await state()).session.index].structurePractice,true);
 for(let i=0;i<20;i++){const current=(await state()).session.steps[(await state()).session.index];if(current.type==='listen'){assert.equal(await evaluate("document.querySelectorAll('.word-chunk,#word-structure-guide').length"),0);break;}await submitAnswer(current.answer);}
 await finishExercises();await click('#finish-lesson');
 // Dictation recap timing, pause/replay, persistence and settings.
 async function recapFixture(seconds=2){
  await evaluate(`const s=JSON.parse(localStorage.getItem('a-little-english-v2'));s.settings.dictationDelay=${seconds};s.session={kind:'words',memoryVersion:1,title:'听写回看验证',progressionVersion:2,index:0,firstTry:0,wrong:[],wordKeys:['water'],steps:[{type:'listen',title:'听声音写单词',answer:'water',key:'water',wholeAnswer:true},{type:'letter',word:'A'}]};localStorage.setItem('a-little-english-v2',JSON.stringify(s));location.reload()`);
  await delay(300);await ready();await click('#start-lesson');
 }
 await recapFixture();assert.equal(await hintVisible(),false);await submitAnswer('water',false);
 assert.equal((await state()).session.index,0);assert.equal(await hintVisible(),true);assert.equal((await state()).session.firstTry,1);assert.equal((await state()).session.steps[0].blankState.hintUsed,false);
 await delay(700);assert.equal((await state()).session.index,0);await wait("!document.querySelector('#dictation-review-status')");assert.equal((await state()).session.index,1);await click('#close-lesson');
 await recapFixture();await submitAnswer('water',false);await click('#pause-dictation');await delay(2200);assert.equal((await state()).session.index,0);
 await click('#close-lesson');await evaluate('location.reload()');await delay(300);await ready();await click('#start-lesson');await wait("!!document.querySelector('#dictation-review-status')");assert.equal(await hintVisible(),true);assert.equal((await state()).session.firstTry,1);assert.equal((await state()).session.steps[0].reviewPaused,true);
 await click('#next-step');await delay(2200);assert.equal((await state()).session.index,1);await click('#close-lesson');
 await recapFixture();await submitAnswer('water',false);await click('[data-speed="normal"]');assert.equal((await state()).session.steps[0].reviewPaused,true);await delay(2200);assert.equal((await state()).session.index,0);await click('#close-lesson');
 await recapFixture(4);await submitAnswer('water',false);await delay(2200);assert.equal((await state()).session.index,0);await wait("!document.querySelector('#dictation-review-status')");assert.equal((await state()).session.index,1);await click('#close-lesson');
 await recapFixture(0);await submitAnswer('woter',false);await submitAnswer('water',false);await delay(2200);assert.equal(await hintVisible(),true);assert.equal((await state()).session.index,0);assert.equal((await state()).session.firstTry,0);await click('#next-step');assert.equal((await state()).session.index,1);await click('#close-lesson');
 await recapFixture();await submitAnswer('water',false);await click('#close-lesson');await delay(2200);assert.equal((await state()).session.index,0);
 await click('[data-view="settings"]');await evaluate("document.querySelector('#dictation-delay').value='4';document.querySelector('#dictation-delay').dispatchEvent(new Event('change'))");await evaluate('location.reload()');await delay(300);await ready();assert.equal((await state()).settings.dictationDelay,4);assert.equal(await evaluate("document.querySelector('#dictation-delay').value"),'4');
 assert.deepEqual(errors,[]);console.log('PASS: letters validate on input without submit controls, composition waits until committed, wrong letters stay selected, paste validates automatically; correct answers advance automatically, completed saved blanks advance without duplicate credit, partial answers stay editable; individual letter underlines for all writing, fixed punctuation, Chinese below, old whole-word progress migration, inline letter/word inputs, locked partial answers persist after reload, no extra answer box, full exam counts, library pagination/search/filter, shared learned colors, persisted collection and daily assignment, length-based random progressive letter gaps, 1/multiple word sentence gaps, resume without duplicate stages, centered translation and phonetics, gap wrong/retry/reveal, legacy session upgrade, migration, new lesson, resume after reload, wrong-answer retry, daily limit, full course library, grammar completion, microphone recording/playback, speaking completion, dictionary search/add, settings, MP3 audio, 7 views at 390px and 320px; no runtime errors.');ws.close();chrome.kill();
})().catch(e=>{console.error(e);chrome.kill();process.exitCode=1;});
